import { describe, expect, it } from "vitest";
import {
  isLocalBackupFilename,
  localBackupFilename,
  localModEntry,
  profilePathFromIni,
  validateManifest,
  zenProcessIsRunning,
} from "./install-local-core.mjs";
import {
  localInstallCommand,
  parseRestartArguments,
} from "./install-local-restart-core.mjs";

describe("local Sine backup filenames", () => {
  const filename = "mods.json.bak-local-2026-08-08T15-53-03-742Z";

  it("generates the timestamped name used by the installer", () => {
    expect(localBackupFilename(new Date("2026-08-08T15:53:03.742Z"))).toBe(filename);
  });

  it("matches only backups generated by the local installer", () => {
    expect(isLocalBackupFilename(filename)).toBe(true);
    expect(isLocalBackupFilename("mods.json")).toBe(false);
    expect(isLocalBackupFilename("mods.json.bak")).toBe(false);
    expect(isLocalBackupFilename("mods.json.bak-local-not-a-timestamp")).toBe(false);
    expect(isLocalBackupFilename(`${filename}.tmp`)).toBe(false);
  });
});

describe("profilePathFromIni", () => {
  it("resolves the relative default profile", () => {
    const ini = `
[Profile0]
Name=Default
IsRelative=1
Path=Profiles/abc.default
Default=1

[Profile1]
Name=Other
IsRelative=1
Path=Profiles/other.default
`;

    expect(profilePathFromIni(ini, "/zen-root")).toBe("/zen-root/Profiles/abc.default");
  });

  it("preserves an absolute default profile path", () => {
    const ini = `
[Profile0]
IsRelative=0
Path=/profiles/zen
Default=1
`;

    expect(profilePathFromIni(ini, "/zen-root")).toBe("/profiles/zen");
  });

  it("rejects an ambiguous profile file", () => {
    const ini = `
[Profile0]
Path=Profiles/one
Default=1
[Profile1]
Path=Profiles/two
Default=1
`;

    expect(() => profilePathFromIni(ini, "/zen-root")).toThrow(
      "exactly one default profile",
    );
  });
});

describe("validateManifest", () => {
  it("accepts a matching Sine mod manifest", () => {
    expect(
      validateManifest(
        {
          id: "tab-deduplicator",
          name: "Tab Deduplicator",
          scripts: { "dist/tab-deduplicator.uc.mjs": {} },
        },
        "tab-deduplicator",
      ),
    ).toBeUndefined();
  });

  it("rejects an id that does not match its directory", () => {
    expect(() =>
      validateManifest({ id: "different", name: "Different" }, "tab-deduplicator"),
    ).toThrow("must match");
  });
});

describe("localModEntry", () => {
  it("uses the manifest and marks the mod as a local no-update install", () => {
    const manifest = {
      id: "tab-deduplicator",
      name: "Tab Deduplicator",
      version: "0.1.0",
    };

    expect(localModEntry(manifest)).toEqual({
      ...manifest,
      origin: "local",
      "no-updates": true,
      enabled: true,
    });
  });

  it("preserves an existing disabled choice and unrelated Sine metadata", () => {
    expect(
      localModEntry(
        { id: "example", name: "New name", version: "2" },
        { id: "example", name: "Old name", enabled: false, stars: 4 },
      ),
    ).toEqual({
      id: "example",
      name: "New name",
      version: "2",
      enabled: false,
      stars: 4,
      origin: "local",
      "no-updates": true,
    });
  });

  it("prunes manifest fields that were removed while preserving Sine runtime state", () => {
    expect(
      localModEntry(
        {
          id: "tab-deduplicator",
          name: "Tab Deduplicator",
          version: "0.3.0",
          scripts: { "dist/tab-deduplicator.uc.mjs": {} },
        },
        {
          id: "tab-deduplicator",
          name: "Tab Deduplicator",
          version: "0.2.0",
          scripts: { "dist/tab-deduplicator.uc.mjs": {} },
          style: { chrome: "styles/chrome.css" },
          preferences: "preferences.json",
          chromeManifest: "sine-chrome.manifest",
          enabled: false,
          origin: "store",
          "no-updates": false,
          stars: 7,
        },
      ),
    ).toEqual({
      id: "tab-deduplicator",
      name: "Tab Deduplicator",
      version: "0.3.0",
      scripts: { "dist/tab-deduplicator.uc.mjs": {} },
      enabled: false,
      origin: "local",
      "no-updates": true,
      stars: 7,
    });
  });
});

describe("zenProcessIsRunning", () => {
  it("recognizes the Zen application process without matching helpers", () => {
    expect(
      zenProcessIsRunning([
        "/Applications/Zen.app/Contents/MacOS/zen --profile /tmp/profile",
        "/Applications/Zen.app/Contents/MacOS/plugin-container -parentPid 42",
      ]),
    ).toBe(true);
  });

  it("does not mistake plugin containers for the browser", () => {
    expect(
      zenProcessIsRunning([
        "/Applications/Zen.app/Contents/MacOS/plugin-container -parentPid 42",
      ]),
    ).toBe(false);
  });
});

describe("restart-aware local install arguments", () => {
  it("parses an individual mod and optional profile", () => {
    expect(
      parseRestartArguments(["tab-deduplicator", "--profile", "/tmp/zen profile"]),
    ).toEqual({
      all: false,
      modId: "tab-deduplicator",
      profile: "/tmp/zen profile",
    });
  });

  it("parses the aggregate action without accepting a mod or profile", () => {
    expect(parseRestartArguments(["--all"])).toEqual({
      all: true,
      modId: null,
      profile: null,
    });
    expect(() => parseRestartArguments(["--all", "keep-loaded"])).toThrow(
      "cannot combine",
    );
    expect(() => parseRestartArguments(["--all", "--profile", "/tmp/zen"])).toThrow(
      "does not accept",
    );
  });

  it("builds individual and aggregate installer commands", () => {
    expect(
      localInstallCommand(
        { all: false, modId: "keep-loaded", profile: "/tmp/zen" },
        { nodePath: "/node", installerPath: "/repo/install-local.mjs" },
      ),
    ).toEqual({
      command: "/node",
      args: ["/repo/install-local.mjs", "keep-loaded", "--profile", "/tmp/zen"],
    });
    expect(
      localInstallCommand(
        { all: true, modId: null, profile: null },
        { nodePath: "/node", installerPath: "/repo/install-local.mjs" },
      ),
    ).toEqual({ command: "pnpm", args: ["run", "install:local:all"] });
  });
});
